"""extend profile fields

Revision ID: f1edc57537f9
Revises: 
Create Date: 2025-09-01 01:05:47.990065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1edc57537f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('ats_type', sa.String(length=80), nullable=False),
    sa.Column('fields_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('skills_csv', sa.Text(), nullable=False),
    sa.Column('resume_path', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qa_pack_id', sa.String(length=120), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('base_answer', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('qa_pack_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_number', sa.String(length=120), nullable=False),
    sa.Column('resume_version', sa.String(length=120), nullable=False),
    sa.Column('cover_letter_version', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('qa_bank')
    op.drop_table('profiles')
    op.drop_table('jobs')
    # ### end Alembic commands ###
